version: '2.3'
services:

  # AMR environemt, not AMMR
  ros_l4t_base:
    build: 
      context: ./ros_l4t
      dockerfile: Dockerfile
    image: airobots_docker:ros_l4t
    container_name: ros_l4t

  aiRobots_AMR:
    build:
      context: ./AMR
      dockerfile: Dockerfile     
    depends_on: [ros_l4t_base]
    image: airobots_docker:aiRobots_AMR
    container_name: aiRobots_AMR
    network_mode: "host"
    runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/aiRobots_AMMR:/home/aiRobots/aiRobots/aiRobots_AMMR/
      - ~/aiRobots/SLAM:/home/aiRobots/aiRobots/SLAM/
      - ~/aiRobots/Datasets:/home/aiRobots/aiRobots/Datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"

  # AMMR environemt, not AMR
  ros_melodic_base:
    build: 
      context: ./ros_melodic
      dockerfile: Dockerfile
    image: airobots_docker:ros_melodic
    container_name: ros_melodic

  aiRobots_AMMR:
    build:
      context: ./AMMR
      dockerfile: Dockerfile     
    depends_on: [ros_l4t_base]
    image: airobots_docker:aiRobots_AMMR
    container_name: aiRobots_AMMR
    network_mode: "host"
    runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/aiRobots_AMMR:/home/aiRobots/aiRobots/aiRobots_AMMR/
      - ~/aiRobots/SLAM:/home/aiRobots/aiRobots/SLAM/
      - ~/aiRobots/Datasets:/home/aiRobots/aiRobots/Datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"